
GET http://localhost:8000/user
subscription: node-api-key-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJub2RlLWFwaS1rZXktand0Iiwic3ViIjoiMTIzNDU2Nzg5MCIsIm5hbWUiOiJKb2huIERvZSIsImlhdCI6MTUxNjIzOTAyMiwiZXhwIjoxNzUwMDM4MTIxfQ.PdIsDSbeYUUrzXIPbcpsNPmJImctHqF_CyARXeJR8l4

###

GET http://localhost:8000/load-balance
subscription: node-api-key-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJub2RlLWFwaS1rZXktand0Iiwic3ViIjoiMTIzNDU2Nzg5MCIsIm5hbWUiOiJKb2huIERvZSIsImlhdCI6MTUxNjIzOTAyMiwiZXhwIjoxNzUwMDM4MTIxfQ.PdIsDSbeYUUrzXIPbcpsNPmJImctHqF_CyARXeJR8l4
